version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/github.com/lzakharov/hlcup2017
    depends_on:
      - db
    command: ["realize", "start"]
  db:
    image: postgres
